version: 2.1
jobs:
  build:
    working_directory: ~/Robot-Scouter
    machine:
      image: ubuntu-1604:201903-01
    environment:
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Dkotlin.incremental=false -Dkotlin.compiler.execution.strategy=in-process
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ .Branch }}
            - v1-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - compare-url/reconstruct
      - run:
          name: Accept Android licenses
          command: |
            mkdir -p "$ANDROID_HOME/licenses"
            echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55\n24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"
            echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd\n504667f4c0de7af1a06de9f4b1727b84351f2910" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
      - run:
          name: Setup environment
          command: |
            > ~/.gitconfig
            chmod +x gradlew && ./gradlew setup --stacktrace
      - run:
          name: Build
          command: |
            # NodeJS settings get reset accross steps, so we need to do this here unfortunatly.
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
            source ~/.bashrc
            nvm install --lts
            nvm use --lts

            ./gradlew clean ciBuild --stacktrace
      - save_cache:
          key: v1-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ .Branch }}-{{ .Revision }}
          when: always
          paths:
            - ~/.gradle
            - ~/android-sdk
orbs:
  compare-url: iynere/compare-url@1.2.0
